//
//  AppIntent.swift
//  SwiftUILearningsWidget
//
//  Created by Saurabh Verma on 30/09/23.
//

import WidgetKit
import AppIntents

struct ConfigurationAppIntent: WidgetConfigurationIntent {
    static var title: LocalizedStringResource = "Configuration"
    static var description = IntentDescription("This is an example widget.")

    // An example configurable parameter.
    @Parameter(title: "Favorite Emoji", default: "😃")
    var favoriteEmoji: String
    
    // Example of a parameter which is added further on the boiler plate code
    // generated by Xcode, this parameter is updated based on value set to shared
    // user defaults in app groups.
    @Parameter(title: "Today's Mood", default: "Not set")
    var mood: String
}
